### ISSUE TITLE
problems with the modification altar

### ISSUE THREAD

**Issue by Kastik404** [YerovaArusu/botanicpledge#18] opened 2024-11-09 15:54 UTC
![изображение](https://github.com/user-attachments/assets/2c099fc8-6f4f-4652-82cd-783bedda526c)
Maybe I'm doing something wrong. I put the sword on the table, press vandom shift right mouse button, the texture in the center changes, I put the runes on the right mouse button, visually they appear for me and for other players, but in fact the stats of the sword do not change and they are not taken from the inventory, after unlocking I take the sword, and it says that it has 4 empty rune sockets, when returning to the altar it also shows that 4 runes are spinning, but at some point after moving the sword back and forth the runes can disappear and everything starts over. This is probably a kernel or build bug. After checking on a clean build without unnecessary mods, everything written above was repeated, but now the runes were not visually inserted, but actually strengthened the sword, but also are not spent from the inventory.

**Comment by YerovaArusu** [comment] 2024-11-09 16:49
Hey, I looked into the issue. it was relatively easy to fix.
Can you test if that bug was fixed on your end by using the generated jar file inside the attached zip file?

[botanicpledge-1.20.1-0.7.4.1_TEST_1.zip](https://github.com/user-attachments/files/17688675/botanicpledge-1.20.1-0.7.4.1_TEST_1.zip)

After testing if this issue is also fixed i will close this issue

**Comment by Kastik404** [comment] 2024-11-09 17:24
The runes are taken from the inventory, everything is fine, at the moment I can’t check it on the modified core, that’s all my powers for now.

**Comment by YerovaArusu** [comment] 2024-11-09 21:06
okay. then i will close this issue for now. Just reopen this issue if the issue is still persistent after that

I will release a new version tomorrow. there this bug will be offically fixed

**Closed as completed by YerovaArusu** 2024-11-09 21:06 UTC
