### ISSUE TITLE
Yggdrasil Guardian - Gaia 3

### ISSUE THREAD

**Issue by Reaviik** [YerovaArusu/botanicpledge#13] opened 2024-10-07 16:58 UTC
During the Gaia 3 battle he adds to the pile of entities and for some reason in some battles the entities don't disappear, which overloads the entity map, I'm still not sure why they don't disappear as they should

![image](https://github.com/user-attachments/assets/253b544a-a840-410c-ba86-efa378cbb37a)
![image](https://github.com/user-attachments/assets/0a1dc8a7-aadd-487d-a2dd-99dff2eb9023)

**Comment by Reaviik** [comment] 2024-10-07 16:59
When I teleport to the entity I can't see it but the mod says it is there, Mod used [Crash Utilities]

**Comment by YerovaArusu** [comment] 2024-10-07 17:16
Yes. I am fully aware of this error. I have been trying to fix this for a while now... But I haven't found a working solution yet...

**Comment by YerovaArusu** [comment] 2024-10-07 21:25
Could you maybe test if that error is still present with the following mod? I dont want to publish anything that does not work. It works in my dev environments.
(The mod is in the zip file)

[Test_Mod.zip](https://github.com/user-attachments/files/17284647/Test_Mod.zip)

**Comment by Reaviik** [comment] 2024-10-09 04:16
If it is compatible with the previous version I can test it because the mod is on a server directly linked to curse forge so it would be necessary to update it

**Comment by YerovaArusu** [comment] 2024-10-09 11:13
Yes. It's directly compatible. Just a few lines of code to address this issue were changed. If I am not mistaken they should currently even have the same name

**Comment by YerovaArusu** [comment] 2024-10-18 21:26
Hello there. Have you already tested if the issue is still present on your end?

**Comment by YerovaArusu** [comment] 2024-10-21 08:48
I`ll close this issue since the issue seems to have been ckeared with the test mod. Official release of version 0.7.3.1 (Bugfix`n Lexica-upgrades) will release later today

**Closed as completed by YerovaArusu** 2024-10-21 08:48 UTC
Labels: bug
